name: Publish package to the ForgeRock artifactory
on:
  release:
    types: [published]
env:
  VERSION: ${{ github.event.release.tag_name }}
  VERSIONDOS: ${{ github.ref }}
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Deploy release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      
      - name: echo values
        run: |
          echo ${{ github.ref }}
          echo $VERSION
          echo $VERIONDOS
          echo "VERSION ${VERSION} - ${{ VERSION }}
          echo "VERSION ${VERSIONDOS} - ${{ VERSIONDOS }} 
          echo $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases/latest

      - name: discover latest releases to push assets
        id: discover_latest_release
        run: |
          curl -H "Accept: application/vnd.github.v3+json" $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases/latest

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
        with:
          upload_url: ${{ steps.upload_release_asset.outputs.upload_url }}
          asset_path: README.md
          asset_name: test-upload-README.md
          asset_content_type: text/markdown
