name: Publish package to the ForgeRock artifactory
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Deploy release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      
      - name: echo values
        run: |
	echo ${{ github.ref }}
	echo ${{ GITHUB_API_URL }}/repos/${{ GITHUB_REPOSITORY }}releases/latest

      - name: discover latest releases to push assets
	id: discover_latest_release
	run: curl ${{ GITHUB_API_URL }}/repos/${{ GITHUB_REPOSITORY }}releases/latest

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
        with:
          upload_url: ${{ steps.discover_latest_release.outputs.upload_url }}
          asset_path: README.md
          asset_name: test-upload-README.md
          asset_content_type: text/markdown
