# This action uses two steps
# - 'Update epic issues with subtasks' step to update epic issues with the subtask issues
# - 'Update epic subtask issues status' step is to update the status of the epic subtasks when the epic issue is labeled as `feature`
# Auto close enabled
name: Update epics
on:
  issues:
    types: [edited, closed, reopened, labeled]
jobs:
  epics:
    if: contains(github.event.issue.labels.*.name, 'subtask')
    runs-on: ubuntu-latest
    name: Update epic issues
    steps:
      - name: Sync Epic Issues
        id: sync-epic
        uses: kiali/kiali-epic-action@v1.0.1
        with:
          TOKEN: ${{ secrets.GH_TOKEN }}
#      - name: Run epics action
#        needs: sync-epic
#        uses: cloudaper/epics-action@v1.1.4
#        with:
#          github-token: ${{ secrets.GH_TOKEN }}
#          epic-label-name: feature
#          auto-close-epic: true
