# This action uses two steps
# - One to update an epic with the issue link that reference an epic
# - Second step is to update the status of the epic subtasks when the epic issue is labeled as `feature`
name: Update epics
on:
  issues:
    types: [edited, closed, reopened, labeled]
jobs:
  epics:
    runs-on: ubuntu-latest
    name: Update epic issues
    steps:
      - name: Sync Epic Issues
        if: contains(github.event.issue.labels.*.name, 'subtask')
        id: sync-epic
        uses: kiali/kiali-epic-action@v1.0.1
        with:
          TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Run epics action
        uses: cloudaper/epics-action@v1.1.4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          epic-label-name: feature
          auto-close-epic: true
