name: Update epics
on:
  issues:
    types: [opened, closed, reopened]
jobs:
  sync-epic-job:
    if: contains(github.event.issue.labels.*.name, 'subtask')
    runs-on: ubuntu-latest
    name: Sync epic issues with subtasks issues
    steps:
      - name: Sync Epic Issues
        id: sync-epic
        uses: kiali/kiali-epic-action@v1.0.1
        with:
          TOKEN: ${{ secrets.GH_TOKEN }}
  epics:
    runs-on: ubuntu-latest
    name: Update epic issues
    steps:
      - name: Run epics action
        uses: cloudaper/epics-action@v1.1.4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          epic-label-name: feature
          auto-close-epic: true
