on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  release_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout by provided tag
        id: checkout-tag
        with:
          ref: ${{ inputs.tag }}
