name: Show versions

on:
  workflow_call:

jobs:
  show:
    name: show values
    runs-on: ubuntu-latest
    steps:
      - name: show docker version
        run: |
          echo "docker version: $(docker --version)"
        
